### ISSUE TITLE
Замечание к лабораторной

### ISSUE THREAD

**Issue by rredbird66** [DaniilPolyakow/lab2pzrl#1]
1. При каких-то ошибках делается печать и return 1, а при каких-то - только печать. Лучше привести к единому виду.
![изображение](https://github.com/DaniilPolyakow/lab2pzrl/assets/36138085/a8407742-6d9a-4997-97c6-123f660b958b)
2. Если б не это - собирался зачесть. Во первых - глобальные переменные - зло. Во вторых - особенно, когда они не используются. Тогда вообще не понятно, для чего они создавались. Вот тут, например, в файле bin.c идёт переопределение переменных, которые были объявлены в bin.h.
![изображение](https://github.com/DaniilPolyakow/lab2pzrl/assets/36138085/5ccec36b-1273-4aa6-946c-7a1c823ffbbe)
Зачем - вообще не понятно. Так что пройдитесь по коду и избавьтесь от всех таких неурядиц и глобальных переменных, где в них нет совершенно никакой необходимости.
3. Неправильный include в hex.c. 
![изображение](https://github.com/DaniilPolyakow/lab2pzrl/assets/36138085/a0448e8e-e0a9-4f64-8ec9-fb9e37d04e4b)
4. Лучше при компиляции добавить флаги -Wextra -Wall

**Comment by rredbird66** [comment]
1. Проигнорировано, ну и ладно.
2. Для чего глобальная переменная myInt в caclulations.h?
3. Отсутствие include - тоже некорректно.
4. Проигнорировано.

:/

**Comment by DaniilPolyakow** [comment]
Извиняюсь, не увидел 😎 (Переделал)
 DaniilPolyakow/lab2pzrl: вторая лабораторная по пзрл (github.com)
<https://github.com/DaniilPolyakow/lab2pzrl>

ср, 20 дек. 2023 г. в 15:39, redbird66 ***@***.***>:

**Comment by rredbird66** [comment]
-Wall и -Wextra необходимо ставить на этапе преобразования из .c в .o, иначе большинство ошибок так и не будут показаны. Эти опции больше относятся к работе линтера и препроцессора, и практически (или даже совсем) не влияют на работу линкера.

Лабораторная работа 2 зачтена.
